# Generated by Django 5.2.6 on 2025-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_is_featured_product_promo_remove_product_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_to_cart_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
