# Generated by Django 5.2.6 on 2025-10-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_added_to_cart_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='added_to_cart_count',
            new_name='cart_count',
        ),
    ]
