# Generated by Django 5.2.6 on 2025-10-07 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_cart_count_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
